### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by usbsnowcrash** [dzuk-mutant/blockchain#2]
The json file found here https://raw.githubusercontent.com/dzuk-mutant/blockchain/master/blockchain.json does not parse because it is missing a comma making it unusable for automated blocking.
<img width="529" alt="screenshot 2018-04-06 03 27 59" src="https://user-images.githubusercontent.com/882850/38408219-8fff8dde-394a-11e8-83dd-4115304ccb2c.png">

I have corrected the issue in the following PR https://github.com/dzuk-mutant/blockchain/pull/3

**Comment by dzuk-mutant** [comment]
I just published my own fix before I could read that you had made a PR. It should be fine now!
