### ISSUE TITLE
remove social.i2p.rocks from blocklist

### ISSUE THREAD

**Issue by majestrate** [dzuk-mutant/blockchain#4]
"The two main users of this instance has some really fucked up and fascist-leaning opinions and posts."

This is not true, social.i2p.rocks is a small general purpose SFW instance.

Please remove, thanks.

**Comment by mike-burns** [comment]
Like so?

https://social.i2p.rocks/notice/1045235

**Comment by majestrate** [comment]
I don't understand the question? Rephrase.

**Comment by majestrate** [comment]
nevermind, this blocklist is a good thing, it keeps the idiots out of my timeline.

10 / 10 put everyone else cool on this list too.

**Comment by dzuk-mutant** [comment]
like this

![fbc996ef9789c6a7451d6](https://user-images.githubusercontent.com/32108484/38765192-07c8b276-3fb5-11e8-9b4a-0467e0823a93.png)

🙄
