### ISSUE TITLE
Remove gs.archae.me from the blocklist

### ISSUE THREAD

**Issue by archaeme** [dzuk-mutant/blockchain#6]
I've taken it offline for several months now.

**Comment by dzuk-mutant** [comment]
That's okay, there are other defunct instances that are on this list. I'm only going to remove them if they have been reopened by new owners and/or with different enough priorities or moderation philosophies to not be on the blocklist anymore.

**Comment by archaeme** [comment]
Is there a reason why you don't remove defunct instances from the list?

**Comment by dzuk-mutant** [comment]
Yeah, in case it's existing owner uses the domain again.
